/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: v1/geobuf.proto */

#ifndef PROTOBUF_C_v1_2fgeobuf_2eproto__INCLUDED
#define PROTOBUF_C_v1_2fgeobuf_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Grass__V1__Geobuf Grass__V1__Geobuf;
typedef struct _Grass__V1__Value Grass__V1__Value;
typedef struct _Grass__V1__Properties Grass__V1__Properties;
typedef struct _Grass__V1__Feature Grass__V1__Feature;
typedef struct _Grass__V1__FeatureCollection Grass__V1__FeatureCollection;
typedef struct _Grass__V1__Geometry Grass__V1__Geometry;


/* --- enums --- */

typedef enum _Grass__V1__GeometryType {
  GRASS__V1__GEOMETRY_TYPE__GEOMETRY_TYPE_INVALID = 0,
  GRASS__V1__GEOMETRY_TYPE__GEOMETRY_TYPE_POINT = 1,
  GRASS__V1__GEOMETRY_TYPE__GEOMETRY_TYPE_MULTIPOINT = 2,
  GRASS__V1__GEOMETRY_TYPE__GEOMETRY_TYPE_LINESTRING = 3,
  GRASS__V1__GEOMETRY_TYPE__GEOMETRY_TYPE_MULTILINESTRING = 4,
  GRASS__V1__GEOMETRY_TYPE__GEOMETRY_TYPE_POLYGON = 5,
  GRASS__V1__GEOMETRY_TYPE__GEOMETRY_TYPE_MULTIPOLYGON = 6,
  GRASS__V1__GEOMETRY_TYPE__GEOMETRY_TYPE_GEOMETRYCOLLECTION = 7
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(GRASS__V1__GEOMETRY_TYPE)
} Grass__V1__GeometryType;

/* --- messages --- */

typedef enum {
  GRASS__V1__GEOBUF__DATA_TYPE__NOT_SET = 0,
  GRASS__V1__GEOBUF__DATA_TYPE_FEATURE_COLLECTION = 3,
  GRASS__V1__GEOBUF__DATA_TYPE_FEATURE = 4,
  GRASS__V1__GEOBUF__DATA_TYPE_GEOMETRY = 5
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(GRASS__V1__GEOBUF__DATA_TYPE)
} Grass__V1__Geobuf__DataTypeCase;

struct  _Grass__V1__Geobuf
{
  ProtobufCMessage base;
  /*
   * Number of digits after decimal point for coordinates
   */
  uint32_t precision;
  /*
   * Unique keys of properties
   */
  size_t n_keys;
  char **keys;
  Grass__V1__Geobuf__DataTypeCase data_type_case;
  union {
    Grass__V1__FeatureCollection *feature_collection;
    Grass__V1__Feature *feature;
    Grass__V1__Geometry *geometry;
  };
};
#define GRASS__V1__GEOBUF__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&grass__v1__geobuf__descriptor) \
    , 0, 0,NULL, GRASS__V1__GEOBUF__DATA_TYPE__NOT_SET, {0} }


typedef enum {
  GRASS__V1__VALUE__VALUE_TYPE__NOT_SET = 0,
  GRASS__V1__VALUE__VALUE_TYPE_STRING_VALUE = 1,
  GRASS__V1__VALUE__VALUE_TYPE_DOUBLE_VALUE = 2,
  GRASS__V1__VALUE__VALUE_TYPE_INTEGER_VALUE = 3,
  GRASS__V1__VALUE__VALUE_TYPE_BOOL_VALUE = 4
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(GRASS__V1__VALUE__VALUE_TYPE)
} Grass__V1__Value__ValueTypeCase;

struct  _Grass__V1__Value
{
  ProtobufCMessage base;
  Grass__V1__Value__ValueTypeCase value_type_case;
  union {
    char *string_value;
    double double_value;
    int64_t integer_value;
    protobuf_c_boolean bool_value;
  };
};
#define GRASS__V1__VALUE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&grass__v1__value__descriptor) \
    , GRASS__V1__VALUE__VALUE_TYPE__NOT_SET, {0} }


struct  _Grass__V1__Properties
{
  ProtobufCMessage base;
  /*
   * List of key indecies
   */
  size_t n_keys;
  uint32_t *keys;
  /*
   * Values for the properties
   */
  size_t n_values;
  Grass__V1__Value **values;
};
#define GRASS__V1__PROPERTIES__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&grass__v1__properties__descriptor) \
    , 0,NULL, 0,NULL }


struct  _Grass__V1__Feature
{
  ProtobufCMessage base;
  char *id;
  /*
   * Feature geometry
   */
  Grass__V1__Geometry *geometry;
  /*
   * Feature properties
   */
  Grass__V1__Properties *properties;
};
#define GRASS__V1__FEATURE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&grass__v1__feature__descriptor) \
    , (char *)protobuf_c_empty_string, NULL, NULL }


struct  _Grass__V1__FeatureCollection
{
  ProtobufCMessage base;
  char *id;
  /*
   * List of features
   */
  size_t n_features;
  Grass__V1__Feature **features;
  /*
   * Feature properties
   */
  Grass__V1__Properties *properties;
};
#define GRASS__V1__FEATURE_COLLECTION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&grass__v1__feature_collection__descriptor) \
    , (char *)protobuf_c_empty_string, 0,NULL, NULL }


struct  _Grass__V1__Geometry
{
  ProtobufCMessage base;
  char *id;
  /*
   * Type of geometry
   */
  Grass__V1__GeometryType type;
  /*
   * Geometries length, for example 2D point will be saved as 2.
   */
  size_t n_lengths;
  uint32_t *lengths;
  /*
   * List of coordinates values.
   */
  size_t n_coords;
  int64_t *coords;
  /*
   * This field only used for GEOMETRY_TYPE_GEOMETRYCOLLECTION.
   * TODO(nk2ge5k): it might be worth to remove this type.
   */
  size_t n_geometries;
  Grass__V1__Geometry **geometries;
  /*
   * Feature properties
   */
  Grass__V1__Properties *properties;
};
#define GRASS__V1__GEOMETRY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&grass__v1__geometry__descriptor) \
    , (char *)protobuf_c_empty_string, GRASS__V1__GEOMETRY_TYPE__GEOMETRY_TYPE_INVALID, 0,NULL, 0,NULL, 0,NULL, NULL }


/* Grass__V1__Geobuf methods */
void   grass__v1__geobuf__init
                     (Grass__V1__Geobuf         *message);
size_t grass__v1__geobuf__get_packed_size
                     (const Grass__V1__Geobuf   *message);
size_t grass__v1__geobuf__pack
                     (const Grass__V1__Geobuf   *message,
                      uint8_t             *out);
size_t grass__v1__geobuf__pack_to_buffer
                     (const Grass__V1__Geobuf   *message,
                      ProtobufCBuffer     *buffer);
Grass__V1__Geobuf *
       grass__v1__geobuf__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   grass__v1__geobuf__free_unpacked
                     (Grass__V1__Geobuf *message,
                      ProtobufCAllocator *allocator);
/* Grass__V1__Value methods */
void   grass__v1__value__init
                     (Grass__V1__Value         *message);
size_t grass__v1__value__get_packed_size
                     (const Grass__V1__Value   *message);
size_t grass__v1__value__pack
                     (const Grass__V1__Value   *message,
                      uint8_t             *out);
size_t grass__v1__value__pack_to_buffer
                     (const Grass__V1__Value   *message,
                      ProtobufCBuffer     *buffer);
Grass__V1__Value *
       grass__v1__value__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   grass__v1__value__free_unpacked
                     (Grass__V1__Value *message,
                      ProtobufCAllocator *allocator);
/* Grass__V1__Properties methods */
void   grass__v1__properties__init
                     (Grass__V1__Properties         *message);
size_t grass__v1__properties__get_packed_size
                     (const Grass__V1__Properties   *message);
size_t grass__v1__properties__pack
                     (const Grass__V1__Properties   *message,
                      uint8_t             *out);
size_t grass__v1__properties__pack_to_buffer
                     (const Grass__V1__Properties   *message,
                      ProtobufCBuffer     *buffer);
Grass__V1__Properties *
       grass__v1__properties__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   grass__v1__properties__free_unpacked
                     (Grass__V1__Properties *message,
                      ProtobufCAllocator *allocator);
/* Grass__V1__Feature methods */
void   grass__v1__feature__init
                     (Grass__V1__Feature         *message);
size_t grass__v1__feature__get_packed_size
                     (const Grass__V1__Feature   *message);
size_t grass__v1__feature__pack
                     (const Grass__V1__Feature   *message,
                      uint8_t             *out);
size_t grass__v1__feature__pack_to_buffer
                     (const Grass__V1__Feature   *message,
                      ProtobufCBuffer     *buffer);
Grass__V1__Feature *
       grass__v1__feature__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   grass__v1__feature__free_unpacked
                     (Grass__V1__Feature *message,
                      ProtobufCAllocator *allocator);
/* Grass__V1__FeatureCollection methods */
void   grass__v1__feature_collection__init
                     (Grass__V1__FeatureCollection         *message);
size_t grass__v1__feature_collection__get_packed_size
                     (const Grass__V1__FeatureCollection   *message);
size_t grass__v1__feature_collection__pack
                     (const Grass__V1__FeatureCollection   *message,
                      uint8_t             *out);
size_t grass__v1__feature_collection__pack_to_buffer
                     (const Grass__V1__FeatureCollection   *message,
                      ProtobufCBuffer     *buffer);
Grass__V1__FeatureCollection *
       grass__v1__feature_collection__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   grass__v1__feature_collection__free_unpacked
                     (Grass__V1__FeatureCollection *message,
                      ProtobufCAllocator *allocator);
/* Grass__V1__Geometry methods */
void   grass__v1__geometry__init
                     (Grass__V1__Geometry         *message);
size_t grass__v1__geometry__get_packed_size
                     (const Grass__V1__Geometry   *message);
size_t grass__v1__geometry__pack
                     (const Grass__V1__Geometry   *message,
                      uint8_t             *out);
size_t grass__v1__geometry__pack_to_buffer
                     (const Grass__V1__Geometry   *message,
                      ProtobufCBuffer     *buffer);
Grass__V1__Geometry *
       grass__v1__geometry__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   grass__v1__geometry__free_unpacked
                     (Grass__V1__Geometry *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Grass__V1__Geobuf_Closure)
                 (const Grass__V1__Geobuf *message,
                  void *closure_data);
typedef void (*Grass__V1__Value_Closure)
                 (const Grass__V1__Value *message,
                  void *closure_data);
typedef void (*Grass__V1__Properties_Closure)
                 (const Grass__V1__Properties *message,
                  void *closure_data);
typedef void (*Grass__V1__Feature_Closure)
                 (const Grass__V1__Feature *message,
                  void *closure_data);
typedef void (*Grass__V1__FeatureCollection_Closure)
                 (const Grass__V1__FeatureCollection *message,
                  void *closure_data);
typedef void (*Grass__V1__Geometry_Closure)
                 (const Grass__V1__Geometry *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    grass__v1__geometry_type__descriptor;
extern const ProtobufCMessageDescriptor grass__v1__geobuf__descriptor;
extern const ProtobufCMessageDescriptor grass__v1__value__descriptor;
extern const ProtobufCMessageDescriptor grass__v1__properties__descriptor;
extern const ProtobufCMessageDescriptor grass__v1__feature__descriptor;
extern const ProtobufCMessageDescriptor grass__v1__feature_collection__descriptor;
extern const ProtobufCMessageDescriptor grass__v1__geometry__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_v1_2fgeobuf_2eproto__INCLUDED */
