/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: v1/geobuf.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "geobuf.pb-c.h"
void   grass__v1__geobuf__init
                     (Grass__V1__Geobuf         *message)
{
  static const Grass__V1__Geobuf init_value = GRASS__V1__GEOBUF__INIT;
  *message = init_value;
}
size_t grass__v1__geobuf__get_packed_size
                     (const Grass__V1__Geobuf *message)
{
  assert(message->base.descriptor == &grass__v1__geobuf__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t grass__v1__geobuf__pack
                     (const Grass__V1__Geobuf *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &grass__v1__geobuf__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t grass__v1__geobuf__pack_to_buffer
                     (const Grass__V1__Geobuf *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &grass__v1__geobuf__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Grass__V1__Geobuf *
       grass__v1__geobuf__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Grass__V1__Geobuf *)
     protobuf_c_message_unpack (&grass__v1__geobuf__descriptor,
                                allocator, len, data);
}
void   grass__v1__geobuf__free_unpacked
                     (Grass__V1__Geobuf *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &grass__v1__geobuf__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   grass__v1__value__init
                     (Grass__V1__Value         *message)
{
  static const Grass__V1__Value init_value = GRASS__V1__VALUE__INIT;
  *message = init_value;
}
size_t grass__v1__value__get_packed_size
                     (const Grass__V1__Value *message)
{
  assert(message->base.descriptor == &grass__v1__value__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t grass__v1__value__pack
                     (const Grass__V1__Value *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &grass__v1__value__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t grass__v1__value__pack_to_buffer
                     (const Grass__V1__Value *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &grass__v1__value__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Grass__V1__Value *
       grass__v1__value__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Grass__V1__Value *)
     protobuf_c_message_unpack (&grass__v1__value__descriptor,
                                allocator, len, data);
}
void   grass__v1__value__free_unpacked
                     (Grass__V1__Value *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &grass__v1__value__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   grass__v1__properties__init
                     (Grass__V1__Properties         *message)
{
  static const Grass__V1__Properties init_value = GRASS__V1__PROPERTIES__INIT;
  *message = init_value;
}
size_t grass__v1__properties__get_packed_size
                     (const Grass__V1__Properties *message)
{
  assert(message->base.descriptor == &grass__v1__properties__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t grass__v1__properties__pack
                     (const Grass__V1__Properties *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &grass__v1__properties__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t grass__v1__properties__pack_to_buffer
                     (const Grass__V1__Properties *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &grass__v1__properties__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Grass__V1__Properties *
       grass__v1__properties__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Grass__V1__Properties *)
     protobuf_c_message_unpack (&grass__v1__properties__descriptor,
                                allocator, len, data);
}
void   grass__v1__properties__free_unpacked
                     (Grass__V1__Properties *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &grass__v1__properties__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   grass__v1__feature__init
                     (Grass__V1__Feature         *message)
{
  static const Grass__V1__Feature init_value = GRASS__V1__FEATURE__INIT;
  *message = init_value;
}
size_t grass__v1__feature__get_packed_size
                     (const Grass__V1__Feature *message)
{
  assert(message->base.descriptor == &grass__v1__feature__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t grass__v1__feature__pack
                     (const Grass__V1__Feature *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &grass__v1__feature__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t grass__v1__feature__pack_to_buffer
                     (const Grass__V1__Feature *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &grass__v1__feature__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Grass__V1__Feature *
       grass__v1__feature__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Grass__V1__Feature *)
     protobuf_c_message_unpack (&grass__v1__feature__descriptor,
                                allocator, len, data);
}
void   grass__v1__feature__free_unpacked
                     (Grass__V1__Feature *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &grass__v1__feature__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   grass__v1__feature_collection__init
                     (Grass__V1__FeatureCollection         *message)
{
  static const Grass__V1__FeatureCollection init_value = GRASS__V1__FEATURE_COLLECTION__INIT;
  *message = init_value;
}
size_t grass__v1__feature_collection__get_packed_size
                     (const Grass__V1__FeatureCollection *message)
{
  assert(message->base.descriptor == &grass__v1__feature_collection__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t grass__v1__feature_collection__pack
                     (const Grass__V1__FeatureCollection *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &grass__v1__feature_collection__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t grass__v1__feature_collection__pack_to_buffer
                     (const Grass__V1__FeatureCollection *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &grass__v1__feature_collection__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Grass__V1__FeatureCollection *
       grass__v1__feature_collection__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Grass__V1__FeatureCollection *)
     protobuf_c_message_unpack (&grass__v1__feature_collection__descriptor,
                                allocator, len, data);
}
void   grass__v1__feature_collection__free_unpacked
                     (Grass__V1__FeatureCollection *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &grass__v1__feature_collection__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   grass__v1__geometry__init
                     (Grass__V1__Geometry         *message)
{
  static const Grass__V1__Geometry init_value = GRASS__V1__GEOMETRY__INIT;
  *message = init_value;
}
size_t grass__v1__geometry__get_packed_size
                     (const Grass__V1__Geometry *message)
{
  assert(message->base.descriptor == &grass__v1__geometry__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t grass__v1__geometry__pack
                     (const Grass__V1__Geometry *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &grass__v1__geometry__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t grass__v1__geometry__pack_to_buffer
                     (const Grass__V1__Geometry *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &grass__v1__geometry__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Grass__V1__Geometry *
       grass__v1__geometry__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Grass__V1__Geometry *)
     protobuf_c_message_unpack (&grass__v1__geometry__descriptor,
                                allocator, len, data);
}
void   grass__v1__geometry__free_unpacked
                     (Grass__V1__Geometry *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &grass__v1__geometry__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor grass__v1__geobuf__field_descriptors[5] =
{
  {
    "precision",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Grass__V1__Geobuf, precision),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "keys",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(Grass__V1__Geobuf, n_keys),
    offsetof(Grass__V1__Geobuf, keys),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "feature_collection",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Grass__V1__Geobuf, data_type_case),
    offsetof(Grass__V1__Geobuf, feature_collection),
    &grass__v1__feature_collection__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "feature",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Grass__V1__Geobuf, data_type_case),
    offsetof(Grass__V1__Geobuf, feature),
    &grass__v1__feature__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "geometry",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Grass__V1__Geobuf, data_type_case),
    offsetof(Grass__V1__Geobuf, geometry),
    &grass__v1__geometry__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned grass__v1__geobuf__field_indices_by_name[] = {
  3,   /* field[3] = feature */
  2,   /* field[2] = feature_collection */
  4,   /* field[4] = geometry */
  1,   /* field[1] = keys */
  0,   /* field[0] = precision */
};
static const ProtobufCIntRange grass__v1__geobuf__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor grass__v1__geobuf__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "grass.v1.Geobuf",
  "Geobuf",
  "Grass__V1__Geobuf",
  "grass.v1",
  sizeof(Grass__V1__Geobuf),
  5,
  grass__v1__geobuf__field_descriptors,
  grass__v1__geobuf__field_indices_by_name,
  1,  grass__v1__geobuf__number_ranges,
  (ProtobufCMessageInit) grass__v1__geobuf__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor grass__v1__value__field_descriptors[4] =
{
  {
    "string_value",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    offsetof(Grass__V1__Value, value_type_case),
    offsetof(Grass__V1__Value, string_value),
    NULL,
    &protobuf_c_empty_string,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "double_value",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    offsetof(Grass__V1__Value, value_type_case),
    offsetof(Grass__V1__Value, double_value),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "integer_value",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_SINT64,
    offsetof(Grass__V1__Value, value_type_case),
    offsetof(Grass__V1__Value, integer_value),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bool_value",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(Grass__V1__Value, value_type_case),
    offsetof(Grass__V1__Value, bool_value),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned grass__v1__value__field_indices_by_name[] = {
  3,   /* field[3] = bool_value */
  1,   /* field[1] = double_value */
  2,   /* field[2] = integer_value */
  0,   /* field[0] = string_value */
};
static const ProtobufCIntRange grass__v1__value__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor grass__v1__value__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "grass.v1.Value",
  "Value",
  "Grass__V1__Value",
  "grass.v1",
  sizeof(Grass__V1__Value),
  4,
  grass__v1__value__field_descriptors,
  grass__v1__value__field_indices_by_name,
  1,  grass__v1__value__number_ranges,
  (ProtobufCMessageInit) grass__v1__value__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor grass__v1__properties__field_descriptors[2] =
{
  {
    "keys",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Grass__V1__Properties, n_keys),
    offsetof(Grass__V1__Properties, keys),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "values",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Grass__V1__Properties, n_values),
    offsetof(Grass__V1__Properties, values),
    &grass__v1__value__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned grass__v1__properties__field_indices_by_name[] = {
  0,   /* field[0] = keys */
  1,   /* field[1] = values */
};
static const ProtobufCIntRange grass__v1__properties__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor grass__v1__properties__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "grass.v1.Properties",
  "Properties",
  "Grass__V1__Properties",
  "grass.v1",
  sizeof(Grass__V1__Properties),
  2,
  grass__v1__properties__field_descriptors,
  grass__v1__properties__field_indices_by_name,
  1,  grass__v1__properties__number_ranges,
  (ProtobufCMessageInit) grass__v1__properties__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor grass__v1__feature__field_descriptors[3] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Grass__V1__Feature, id),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "geometry",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Grass__V1__Feature, geometry),
    &grass__v1__geometry__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "properties",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Grass__V1__Feature, properties),
    &grass__v1__properties__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned grass__v1__feature__field_indices_by_name[] = {
  1,   /* field[1] = geometry */
  0,   /* field[0] = id */
  2,   /* field[2] = properties */
};
static const ProtobufCIntRange grass__v1__feature__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 10, 2 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor grass__v1__feature__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "grass.v1.Feature",
  "Feature",
  "Grass__V1__Feature",
  "grass.v1",
  sizeof(Grass__V1__Feature),
  3,
  grass__v1__feature__field_descriptors,
  grass__v1__feature__field_indices_by_name,
  2,  grass__v1__feature__number_ranges,
  (ProtobufCMessageInit) grass__v1__feature__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor grass__v1__feature_collection__field_descriptors[3] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Grass__V1__FeatureCollection, id),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "features",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Grass__V1__FeatureCollection, n_features),
    offsetof(Grass__V1__FeatureCollection, features),
    &grass__v1__feature__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "properties",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Grass__V1__FeatureCollection, properties),
    &grass__v1__properties__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned grass__v1__feature_collection__field_indices_by_name[] = {
  1,   /* field[1] = features */
  0,   /* field[0] = id */
  2,   /* field[2] = properties */
};
static const ProtobufCIntRange grass__v1__feature_collection__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 10, 2 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor grass__v1__feature_collection__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "grass.v1.FeatureCollection",
  "FeatureCollection",
  "Grass__V1__FeatureCollection",
  "grass.v1",
  sizeof(Grass__V1__FeatureCollection),
  3,
  grass__v1__feature_collection__field_descriptors,
  grass__v1__feature_collection__field_indices_by_name,
  2,  grass__v1__feature_collection__number_ranges,
  (ProtobufCMessageInit) grass__v1__feature_collection__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor grass__v1__geometry__field_descriptors[6] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Grass__V1__Geometry, id),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Grass__V1__Geometry, type),
    &grass__v1__geometry_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lengths",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Grass__V1__Geometry, n_lengths),
    offsetof(Grass__V1__Geometry, lengths),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "coords",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_SINT64,
    offsetof(Grass__V1__Geometry, n_coords),
    offsetof(Grass__V1__Geometry, coords),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "geometries",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Grass__V1__Geometry, n_geometries),
    offsetof(Grass__V1__Geometry, geometries),
    &grass__v1__geometry__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "properties",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Grass__V1__Geometry, properties),
    &grass__v1__properties__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned grass__v1__geometry__field_indices_by_name[] = {
  3,   /* field[3] = coords */
  4,   /* field[4] = geometries */
  0,   /* field[0] = id */
  2,   /* field[2] = lengths */
  5,   /* field[5] = properties */
  1,   /* field[1] = type */
};
static const ProtobufCIntRange grass__v1__geometry__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 10, 5 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor grass__v1__geometry__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "grass.v1.Geometry",
  "Geometry",
  "Grass__V1__Geometry",
  "grass.v1",
  sizeof(Grass__V1__Geometry),
  6,
  grass__v1__geometry__field_descriptors,
  grass__v1__geometry__field_indices_by_name,
  2,  grass__v1__geometry__number_ranges,
  (ProtobufCMessageInit) grass__v1__geometry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue grass__v1__geometry_type__enum_values_by_number[8] =
{
  { "GEOMETRY_TYPE_INVALID", "GRASS__V1__GEOMETRY_TYPE__GEOMETRY_TYPE_INVALID", 0 },
  { "GEOMETRY_TYPE_POINT", "GRASS__V1__GEOMETRY_TYPE__GEOMETRY_TYPE_POINT", 1 },
  { "GEOMETRY_TYPE_MULTIPOINT", "GRASS__V1__GEOMETRY_TYPE__GEOMETRY_TYPE_MULTIPOINT", 2 },
  { "GEOMETRY_TYPE_LINESTRING", "GRASS__V1__GEOMETRY_TYPE__GEOMETRY_TYPE_LINESTRING", 3 },
  { "GEOMETRY_TYPE_MULTILINESTRING", "GRASS__V1__GEOMETRY_TYPE__GEOMETRY_TYPE_MULTILINESTRING", 4 },
  { "GEOMETRY_TYPE_POLYGON", "GRASS__V1__GEOMETRY_TYPE__GEOMETRY_TYPE_POLYGON", 5 },
  { "GEOMETRY_TYPE_MULTIPOLYGON", "GRASS__V1__GEOMETRY_TYPE__GEOMETRY_TYPE_MULTIPOLYGON", 6 },
  { "GEOMETRY_TYPE_GEOMETRYCOLLECTION", "GRASS__V1__GEOMETRY_TYPE__GEOMETRY_TYPE_GEOMETRYCOLLECTION", 7 },
};
static const ProtobufCIntRange grass__v1__geometry_type__value_ranges[] = {
{0, 0},{0, 8}
};
static const ProtobufCEnumValueIndex grass__v1__geometry_type__enum_values_by_name[8] =
{
  { "GEOMETRY_TYPE_GEOMETRYCOLLECTION", 7 },
  { "GEOMETRY_TYPE_INVALID", 0 },
  { "GEOMETRY_TYPE_LINESTRING", 3 },
  { "GEOMETRY_TYPE_MULTILINESTRING", 4 },
  { "GEOMETRY_TYPE_MULTIPOINT", 2 },
  { "GEOMETRY_TYPE_MULTIPOLYGON", 6 },
  { "GEOMETRY_TYPE_POINT", 1 },
  { "GEOMETRY_TYPE_POLYGON", 5 },
};
const ProtobufCEnumDescriptor grass__v1__geometry_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "grass.v1.GeometryType",
  "GeometryType",
  "Grass__V1__GeometryType",
  "grass.v1",
  8,
  grass__v1__geometry_type__enum_values_by_number,
  8,
  grass__v1__geometry_type__enum_values_by_name,
  1,
  grass__v1__geometry_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
